Basis-Theory/developers.basistheory.com

docs/blueprints/cards/collect-and-process-cards.mdx

fix: fix broken concepts link

---

docs/blueprints/cards/collect-and-process-cards.mdx
docs/concepts/what-is-the-proxy.mdx

Removes legacy Jekyll templating

fix: remove legacy template

---

docs/sdks/mobile/android/types.mdx

- Adds docs for Android setValueRef and isEditable properties

feat: Adds docs for Android setValueRef and isEditable properties

---

docs/sdks/mobile/ios/types.mdx

- fixes indention and typos on iOS docs

fix: fixes indention and typos on iOS docs

---

docs/api/proxies/proxies.mdx
docs/api/reactors/reactor-formulas.mdx
docs/blueprints/personal-information/query-user-data-from-api.mdx
docs/expressions/detokenization.mdx
docs/guides/collect/index.mdx
docs/guides/govern/control-data-access.mdx
docs/guides/share/index.mdx
docs/guides/share/send-data-to-third-party.mdx

- Fixes curl examples with detokenization expressions and code. Fixes guides card headers.

fix: fix curl examples with code and detokenization expressions

---

docs/api/applications/applications.mdx
docs/api/applications/sessions.mdx
docs/concepts/access-controls.mdx
docs/guides/govern/audit-data-access.mdx
docs/guides/govern/control-data-access.mdx
docs/guides/govern/index.mdx
docs/guides/govern/sessions.mdx
sidebars.js

- Adds `Access Data Using Sessions` guide
- Adds content about sessions to `Access Controls` concept page
- Fixes some related content on other pages
Relevant preview links:
[Guide](https://developers-basistheory-com-git-eng-4001-basis-theory.vercel.app/docs/guides/govern/sessions)
[Concept page](https://developers-basistheory-com-git-eng-4001-basis-theory.vercel.app/docs/concepts/access-controls#what-are-sessions)

feat: Add guide for creating and authorizing sessions

---

docs/api/tenants/tenants.mdx
docs/api/tokens/token-types.mdx
docs/blueprints/cards/collect-and-process-cards.mdx
docs/concepts/what-are-tokens.mdx
docs/sdks/web/react/deprecations.mdx
sidebars.js

feat: add fingerprint default changes, update card blueprint example to use refs, and add react deprecations page

---

docs/sdks/web/react/components.mdx

- feat: add error handling section to react sdk components

feat: add error handling section to react sdk components

---

docs/sdks/web/javascript/methods.mdx

- feat: add cardBin to js change events

feat: add cardBin to js change events

---

docusaurus.config.js

adding redirect from old permissions page

---

docs/sdks/web/javascript/methods.mdx

- adds metadata property details for web elements

feat: adds metadata property details for web elements

---

docs/sdks/mobile/ios/services.mdx

- updates type of API key used for creating sessions

fix: updates type of API key used for creating sessions

---

docs/expressions/filters.mdx
docs/sdks/web/javascript/content-security-policy.mdx
docs/sdks/web/javascript/types.mdx
package.json
src/components/sdks/BasisTheoryComponentDisplay.module.css
src/components/sdks/BasisTheoryComponentDisplay.tsx
src/css/bt-variables.scss
src/typings.d.ts
yarn.lock

Fix embedded Elements colors and CSP text order.
Adds CSP info alert.

Fix: components colors and CSP

---

docs/concepts/access-controls.mdx
docs/concepts/elements.mdx
docs/concepts/index.mdx
docs/guides/govern/sessions.mdx
docs/sdks/mobile/android/index.mdx
docs/sdks/mobile/ios/index.mdx
docs/sdks/web/javascript/index.mdx
sidebars.js

- Adds elements concept page
- Removes repeated content from sdk pages
- Updates links to point to this new concept page

feat: Adds Elements concept page

---

docs/api/tenants/tenants.mdx
docs/api/tokens/token-types.mdx
docs/concepts/what-are-tokens.mdx
docs/expressions/fingerprints.mdx

-  Updates fingerprinting and deduplication docs

feat: Updates fingerprinting and deduplication docs

---

docs/guides/process/analyze-data.mdx

fix: reactor code

---

.github/workflows/deploy.yml

- adding in the notification for deploys starting/ending here

chore: adding deploy notifications

---

.github/workflows/deploy.yml

- removing actions as it can't access them

chore: removing as it cant access a private repo

---

docs/guides/share/index.mdx
docs/guides/share/reveal-tokenized-data.mdx
sidebars.js

- Add guide for revealing tokenized data with Elements

feat: add reveal guide

---

docs/blueprints/cards/index.mdx

- Adds display virtual cards `card` to blueprints homepage.

fix: add display virtual cards blueprint card

---

docs/guides/share/index.mdx
docs/guides/share/reveal-data-from-third-party.mdx
sidebars.js
src/components/shared/Card.tsx

- Adds guide to reveal from a 3rd party.

feat: add reveal from 3rd party guide

---

docs/guides/share/send-data-to-third-party.mdx

Adds tabs to "Send Data to a 3rd Party" guide containing URL encoded example

feat: add application/x-www-form-urlencoded example to share data guide

---

docs/api/rate-limits.mdx

Updating to CF Rate Limits

---

docs/api/rate-limits.mdx

- adds counter to the rate limit docs

Add counter to rate limit docs

---

docs/blueprints/migrations/migrate-off-basis-theory.mdx
docs/concepts/access-controls.mdx
docs/concepts/what-are-reactors.mdx
docs/concepts/what-is-the-proxy.mdx
docs/expressions/index.mdx
docs/index.mdx
docs/sdks/_card-brands.mdx
docs/sdks/web/javascript/index.mdx
docusaurus.config.js

- update doc titles and meta descriptions

feat: update doc titles and meta descriptions

---

docs/index.mdx

- Removing whitespace pattern that rendered on the page
Before
After

fix: Fixing whitespace rendering issue

---

docs/sdks/mobile/ios/index.mdx

- adds details about BasisTheoryUIViewController class

fix: adds details about BasisTheoryUIViewController class

---

docs/sdks/mobile/ios/index.mdx

adding header for UITextFieldDelegate

---

docs/api/tokens/_cvc-ttl-info-alert.mdx
docs/api/tokens/token-types.mdx
docs/api/tokens/tokens.mdx
docs/blueprints/cards/collect-and-process-cards.mdx

- Adding info callouts to reach out to customize the CVC property TTL from the default of 1hr

feat: Documenting CVC TTL behavior

---

docs/api/applications/sessions.mdx

Fixes user-reported documentation error.

Fix Session Authorization C# doc

---

docs/expressions/filters.mdx

feat: documenting alias_card filter

---

docs/guides/collect/collect-cards.mdx

References new `alias_card` filter in Collect Cards guide

fix: reference alias_card in Collect Cards guide

---

docs/api/applications/sessions.mdx
docs/blueprints/cards/issue-and-display-cards.mdx
docs/guides/govern/sessions.mdx

- Update public app permissions for creating sessions

fix: update public app permission to create sessions

---

docs/sdks/_raw-proxy-response.mdx
docs/sdks/mobile/android/services.mdx
docs/sdks/web/javascript/methods.mdx
docs/sdks/web/react/methods.mdx

- feat: adds raw proxy response docs for android

feat: adds raw proxy response docs for android

---

docs/sdks/web/javascript/lifecycle.mdx

- Adds docs for mounting an element using a DOM element instead of a selector.

feat: add docs for mounting to element directly

---

docs/api/tokens/transactions.mdx
docs/concepts/index.mdx
docs/concepts/transactions.mdx
sidebars.js
src/components/shared/Beta.module.css
src/components/shared/Pill.module.css
src/components/shared/Pill.tsx
src/theme/DocSidebarItem/Link/index.js

- Adds API docs for transactions related endpoints
- Adds concept page for transactions

feat: Adds documentation for transactions

---

docs/concepts/what-is-the-proxy.mdx

- adds section for custom domain for proxies

fix: adds section for custom domain for proxies

---

docusaurus.config.js
static/css/kapa.css
static/img/ask-ai-logo.svg

feat: adding kapa to test

---

docs/concepts/what-is-the-proxy.mdx

fix: update hostname docs

---

docs/sdks/_plaintext-http-client-response.mdx
docs/sdks/web/javascript/methods.mdx
docs/sdks/web/react/methods.mdx

- adds docs for http client element calls

feat: adds docs for http client calls for web elements (dual writing)

---

docs/guides/collect/issue-cards.mdx

fix: response_transform in issue-cards.mdx

---

docs/sdks/web/content-security-policy.mdx

- Adds docs for Datadog and LaunchDarkly in the web elements CSP section.
- [] Not Applicable

feat: add dd and ld to elements csp docs

---

docs/sdks/_ios-http-client-response.mdx
docs/sdks/mobile/ios/services.mdx

- adds HTTP client services to iOS

feat: adds HTTP client services to iOS

---

docs/api/proxies/pre-configured-proxies.mdx
docs/api/reactors/reactors.mdx

- Document patch proxies and reactors

Eng 4928 document patch proxies reactors

---

docs/sdks/mobile/android/services.mdx
docs/sdks/mobile/android/types.mdx
docs/sdks/mobile/ios/types.mdx
docs/sdks/web/javascript/methods.mdx

- feat: adds dual write docs to android sdk

feat: adds dual write docs to android sdk

---

package.json
yarn.lock

feat: update packages

---

docusaurus.config.js
package.json

feat: updating kapa to include searching

---

docs/api/proxies/proxies.mdx

- Adding proxy destination timeout note

feat: adding proxy destination timeout info

---

docs/sdks/web/javascript/index.mdx
docs/sdks/web/react/index.mdx

feat: add warning about CRA version to react and js docs

---

docs/api/ip-addresses.mdx

chore: updated Active IP list

---

docs/sdks/web/javascript/index.mdx
docs/sdks/web/react/index.mdx

- Adding link to Basis Theory JS issue

chore: updating issue link

---

docs/concepts/what-are-reactors.mdx

fix: reactor examples

---

docs/api/ip-addresses.mdx

ffix: time of IPs

---

package.json
yarn.lock

feat: update deps

---

docs/api/ip-addresses.mdx
docs/api/rate-limits.mdx

- updating rate limits for searching

Search rate limits

---

docs/api/proxies/pre-configured-proxies.mdx
docs/api/reactors/reactors.mdx

- Document reactors payload size limit

feat: documenting reactors payload size limit

---

docs/sdks/mobile/ios/events.mdx

- Adds new `focus` and `blur` events to iOS docs

feat: add new ios events

---

package.json
yarn.lock

feat: upgrade deps

---

docs/sdks/web/javascript/index.mdx
docs/sdks/web/javascript/options.mdx
docs/sdks/web/react/components.mdx
docs/sdks/web/react/properties.mdx

- feat: adds readOnly and inputMode to JS and React

feat: adds readOnly and inputMode to JS and React

---

docs/api/applications/access-rules.mdx
docs/api/applications/applications.mdx
docs/guides/govern/sessions.mdx
sidebars.js

- making more clear how rules are applied

feat: adding page for Access Rules to better outline logic

---

docs/sdks/web/javascript/types.mdx
docs/sdks/web/react/components.mdx

- Documenting the expiration checks for card element

feat: adding details on card expiration

---

docs/api/proxies/pre-configured-proxies.mdx
docs/api/reactors/reactor-dependencies.mdx
docs/api/reactors/reactor-formulas.mdx
sidebars.js

- Adding a list of all whitelisted npm modules

feat: adding whiteliisted dependencies

---

docs/api/reactors/reactor-dependencies.mdx

feat: add mastercard-client-encryption dependency

---

docs/api/tokens/token-enrichments.mdx

- Missing a few extra contexts for responses and wrong types

fix: updating response to fix gaps

---

docs/api/tokens/token-enrichments.mdx

- adding link from list to codes

feat: adding link to codes

---

docs/api/tokens/token-enrichments.mdx

fix: typo in alpha

---

docs/api/proxies/_custom_headers.mdx
docs/api/proxies/ephemeral-proxy.mdx
docs/api/proxies/pre-configured-proxies.mdx
docs/api/proxies/proxies.mdx

- feat: adds custom headers to response sections

feat: adds custom headers to response sections

---

docs/sdks/mobile/android/options.mdx
docs/sdks/mobile/android/types.mdx

feat: add enableCopy docs for Android

---

docs/guides/share/display-cards.mdx
src/components/docs/_configure-elements-section.mdx
src/pages/index.module.css

- feat: adds react native code samples to display cards guide
Depends on https://github.com/Basis-Theory/basis-theory-react-native/pull/23

feat: adds react native code samples to display cards guide

---

docs/api/ip-addresses.mdx

feat: adding europe ips

---

docs/expressions/detokenization.mdx
docs/guides/process/analyze-data.mdx
docs/guides/process/extract-cards.mdx
package.json
yarn.lock

- feat: update guides to use reactor code instead of formulas

feat: update guides to use reactor code instead of formulas

---

docs/api/errors.mdx
docs/api/proxies/pre-configured-proxies.mdx
docs/api/proxies/proxy-errors.mdx
docs/api/reactors/reactor-errors.mdx
sidebars.js

feat: Adds proxy error docs

---

docs/api/proxies/pre-configured-proxies.mdx

fix: add content type consideration to transform body

---

docs/guides/collect/collect-data-with-android.mdx

Rephrased some things, learning to make changes on docs.
-

Updated verbiage in guide

---

docs/guides/collect/collect-cards.mdx
docs/guides/share/display-cards.mdx
docs/sdks/mobile/react-native/index.mdx
docs/sdks/mobile/react-native/services.mdx

- feat: updates react native docs
- feat: updates collect and reveal guides

feat: updates react native docs

---

docs/api/ip-addresses.mdx

- This removes the IPs that were deprecated

feat: removing ips no longer in service

---

docs/api/applications/sessions.mdx
docs/api/authentication.mdx
docs/api/idempotency.mdx
docs/api/pagination.mdx
docs/api/proxies/pre-configured-proxies.mdx
docs/api/request-correlation.mdx
docs/api/tenants/tenants.mdx
docs/api/tokens/search.mdx
docs/api/tokens/tokenize.mdx
docs/api/tokens/tokens.mdx
docs/guides/collect/set-card-pin.mdx
docs/guides/share/display-cards.mdx

- Fix .NET wrong code examples

fix: fixing code example issues

---

docs/api/reactors/reactor-dependencies.mdx

update reactor dependencies

---

docs/api/tokens/token-enrichments.mdx
docs/blueprints/cards/issue-and-display-cards.mdx
docs/guides/share/reveal-data-from-third-party.mdx
docs/guides/share/reveal-tokenized-data.mdx

fix: add leading slash to internal links

---

docs/features/3d-secure.mdx
docs/features/account-updater.mdx
docs/features/global-data.mdx
docs/features/network-tokens.mdx

fix: add 3ds frictionless faq

---

docs/guides/collect/collect-cards.mdx

Fix grammar in Collect Cards guide

fix: grammar in collect cards guide

---

docs/api/reactors/reactors.mdx
docs/api/tokens/transactions.mdx
docs/concepts/transactions.mdx
docs/concepts/what-are-reactors.mdx
docs/concepts/what-is-search.mdx
docs/features/global-data.mdx
sidebars.js

- Adds enterprise label to async reactors and transactions

feat: Adds enterprise label to async reactors and transactions

---

docs/api/applications/sessions.mdx
docs/concepts/access-controls.mdx

fix: improve sessions description

---

docs/concepts/what-is-the-proxy.mdx
docs/guides/cards/index.mdx
docs/guides/collect/index.mdx
docs/guides/collect/receive-cards.mdx
docs/guides/share/display-cards.mdx
docs/guides/share/process-card-payments.mdx

Just mention webhooks so users can find more information by themselves.

fix: mention webhooks in api guide

---

docs/api/reactors/reactor-dependencies.mdx

Adds shopify package to the reactors dependencies list

fix: document shopify js package in reactor dependencies

---

docs/guides/share/display-cards.mdx

- feat: add readonly to display card guide web elements

feat: add readonly to display card guide web elements

---

docs/api/applications/applications.mdx
docs/api/logs.mdx
docs/api/pagination.mdx
docs/api/proxies/pre-configured-proxies.mdx
docs/api/reactors/reactor-formulas.mdx
docs/api/reactors/reactors.mdx
docs/api/tenants/tenant-members.mdx
docs/api/tokens/search.mdx
docs/api/tokens/tokens.mdx

- Document logs cursor pagination

feat: document logs cursor pagination

---

docs/api/reactors/reactor-dependencies.mdx

fix: upgrade apple pay js

---

docs/guides/share/process-card-payments.mdx

Authorize.net
Checkout
NMI
Paysafe

Add more examples to Guide

---

docs/guides/share/process-card-payments.mdx

feat: add braintree example

---

docs/api/tokens/search.mdx
docs/api/tokens/token-types.mdx
docs/api/tokens/tokens.mdx
docs/concepts/what-is-search.mdx
docs/guides/process/search-data.mdx

- Updates search docs to remove documentation for non `data` and `metadata` searches, and documents limitations.
- Removes docs for listing tokens by type

feat: Updating search docs for data/metadata only, removes list tokens by type

---

docs/api/tokens/search.mdx
docs/api/tokens/tokens.mdx
src/components/sdks/GithubCard.module.css
src/components/sdks/GithubCard.tsx

- Adds docs for single term token id search
- Removes java type filtering example from GetTokens docs
- Fixes styles on GitHub links due to text wrapping

fix: Adds id search docs and other cleanup

---

docs/guides/share/process-card-payments.mdx
src/css/tabs.scss

Before
After
Also, fixes the examples order and highlight in Process Cards guide

fix: tabs text wrap

---

docs/guides/production-checklist.mdx

fix: mention migration in production checklist

---

docs/sdks/web/javascript/options.mdx

- Updates docs to include fonts section for more information on how to use custom fonts

feat: updating section for custom fonts

---

docs/api/rate-limits.mdx
docs/api/reactors/reactors.mdx

fix: move reactors limits to rate limits section

---

docs/api/applications/applications.mdx

fix: Update applications.mdx

---

docs/sdks/mobile/react-native/components.mdx
docs/sdks/web/javascript/options.mdx

- feat: adds text element to react native sdk

feat: adds text element to react native sdk

---

docs/sdks/mobile/android/index.mdx

- Add Android code shrinking and obfuscation warning

feat: add android proguard rules need warning

---

docs/sdks/mobile/android/index.mdx

chore: update android sdk warning

---

docs/blueprints/migrations/import-cards-on-file.mdx
sidebars.js
src/components/shared/PublicKey.module.css
src/components/shared/PublicKey.tsx

feat: add import cards on file guide

---

docs/concepts/what-are-containers.mdx

fix: document container casing behavior

---

docs/sdks/web/javascript/services.mdx
docs/sdks/web/react/services.mdx

- fix: update http client code examples

fix: update http client code examples

---

docs/guides/production-checklist.mdx

fix: add tos mention to production checklist

---

docs/api/reactors/reactor-dependencies.mdx

fix: add google pay js to reactor deps

---

docs/api/rate-limits.mdx

fix: document reactor code length limit

---

docs/guides/banks/collect-bank-accounts.mdx

Fixes Collect Bank Accounts example

fix: move mask from acc to routing nubmer

---

docs/api/tokens/token-enrichments.mdx

**DO NOT MERGE UNTIL WEEK OF 3/11 WHEN PARROT CHANGES GO LIVE**
- Updates Bin Details enrichment docs to match updates documented [here](https://docs.pagos.ai/reference/parrot-batch-data-dictionary)
- Removing arrays from docs where it was used to show ranges of possible values

fix: Updates bin details enrichment documentation

---

docs/api/reactors/reactor-dependencies.mdx

- adds the built-in node dependencies

adding node dependencies

---

docs/guides/apple-pay/overview.mdx
sidebars.js

Add Apple Pay Overview

---

docs/sdks/web/javascript/services.mdx
package.json
yarn.lock

chore: upgrade dependencies

---

docs/guides/share/process-card-payments.mdx

- feat/token:id-doc-card-exp
- minimal

feat/token:id-doc-card-exp

---

docs/guides/process/backup-stripe-tokens.mdx

fix: grammar

---

docs/api/3ds/sessions.mdx
docs/guides/process/authenticate-with-3ds.mdx
docs/sdks/web/3ds/index.mdx

- Add new `pan_token_id` and `authentication_status_code` fields to authenticate api reference
- Add descriptions for all API enum results
- Add test cards list
- Add warning about container ids in web SDK
- Add code examples for other backend languages and SDKs in the guide

feat: update 3ds documentation

---

docs/api/rate-limits.mdx

fix: reactor payload limit

---

docs/blueprints/migrations/import-from-database.mdx
docs/blueprints/personal-information/query-user-data-from-api.mdx
docs/guides/banks/collect-bank-accounts.mdx
docs/guides/banks/process-bank-payments.mdx
docs/guides/collect/collect-cards-single-element.mdx
docs/guides/collect/collect-cards-with-your-inputs.mdx
docs/guides/collect/collect-cards.mdx
docs/guides/collect/issue-cards.mdx
docs/guides/collect/receive-cards.mdx
docs/guides/process/extract-cards.mdx
docs/guides/share/display-cards.mdx
docs/guides/share/process-card-payments.mdx
docs/guides/share/send-data-to-third-party.mdx

- Removing `privacy` as it is no longer a valid field

fix: removing privacy field

---

docs/api/errors.mdx

fix: document 409

---

docs/api/account-updater/account-updater.mdx

- Including correct details on receiving callback details when job statuses change

Updating webhook details for AU

---

docs/api/reactors/reactor-dependencies.mdx
docs/api/reactors/reactor-errors.mdx

feat: add server unavailable error

---

docs/api/reactors/reactor-dependencies.mdx

fix: document fast-xml-parser dep

---

docs/guides/share/process-card-payments-connections.mdx

fix: fixing typo on guide

---

docs/api/reactors/reactor-dependencies.mdx

fix: document snakecase-keys dep

---

docs/api/logs.mdx
docs/api/rate-limits.mdx
docs/api/tokens/_cvc-ttl-info-alert.mdx
docs/api/tokens/token-types.mdx
docs/api/tokens/tokenize.mdx
docs/api/tokens/tokens.mdx

- adding details about default quotas and where to request changes

feat: adding how to request different quotas

---

docs/api/account-updater/account-updater.mdx

- Updates account updater docs to make `merchant_id` optional
- Other refinements

fix: Updates account updater docs to make merchant_id optional

---

docs/api/tokens/token-enrichments.mdx

- Adding documentation to card details enrichment

feat: card details enrichment

---

docs/api/rate-limits.mdx

- updating rate limits to be accurate

feat: rate limits for custom hostnames wrong

---

docs/api/rate-limits.mdx

- Sets actions to the correct ones

feat: updating limit actions

---

docs/concepts/what-are-tokens.mdx

- Adding an example for cards in Token Fingerprint concept

feat: adding card fingerprint example

---

docs/api/tokens/search.mdx
docs/api/tokens/tokens.mdx

- Documenting the slight delay in tokens availability in listing and search

fix: adding information about delay it tokens in list and search

---

docs/api/account-updater/account-updater.mdx
docs/api/pagination.mdx

- Updates cursor pagination docs to match new response contract

fix: Updates cursor pagination docs to match new response contract

---

docs/api/tokens/tokenize.mdx
docs/api/tokens/tokens.mdx

fix: stress deduplication behavior

---

docs/api/deprecations.mdx

- Explains steps to rotate keys for various methods

feat: updating deprecation to include guide on how to update

---

package.json
yarn.lock

- chore: upgrade dev dependencies

chore: upgrade dev dependencies

---

docs/api/deprecations.mdx

- Adding language for rate limits on reactors

feat: adding reactor application limits that were in the email

---

src/components/shared/PublicKey.tsx

fix: fallback pgp key

---

docs/api/proxies/pre-configured-proxies.mdx

ENG-7002 [Docs] Update Pre-configured proxies docs to call out BT-PROXY-URL will not work

---

docs/api/tokens/tokenize.mdx
docs/api/tokens/tokens.mdx

ENG-7004 [Docs] Add fingerprint to token/tokenize requests

---

docs/api/rate-limits.mdx

- Adds API Key AND IP instead of IP for resources

fix: updating to include correct counter

---

docs/api/testing.mdx
docs/api/tokens/_bin-details-test-cards.mdx
docs/api/tokens/token-enrichments.mdx

- Adds testing instruction on how to use `fake` BIN data.

feat: adding fake bin data

---

docs/api/tokens/_bin-details-test-cards.mdx

- Fixing small incorrect value for BIN configuration

fix: removing 'real' as its not a real value

---

docs/guides/share/process-card-payments.mdx

feat: add nuvei example

---

docs/expressions/configuration.mdx
sidebars.js

- Adds documentation for configuration expressions

feat: adding configuration expressions

---

docs/api/orchestration/stripe-forward.mdx
docs/api/tokens/tokens.mdx
docs/sdks/mobile/android/types.mdx

se-219 feat: Review mentions of digits length for expiration_month and expiration_year

---

docs/features/sso/configure-sso-with-oidc.mdx
docs/features/sso/configure-sso-with-okta.mdx
docs/features/sso/configure-sso-with-saml.mdx
docs/features/sso/index.mdx
sidebars.js

- Adds guide for configuring SSO w/ the different Basis Theory supported protocols/providers.

feat: add guides for configuring sso

---

docs/api/orchestration/transactions.mdx

Makes refund transactions docs public

feat: surface refunds documentation

---

docs/api/webhooks/api.mdx
docs/api/webhooks/eventdata.mdx
docs/api/webhooks/webhooks.mdx
sidebars.js

feat: Document Webhooks

---

docs/api/logs.mdx

se-229 feat: explicitly inform that logs only returns cursor pagination

---

docs/api/webhooks/eventdata.mdx

- Adds `actor` information to the event data documentation

fix: Add actor information to event data

---

docs/guides/collect/receive-cards.mdx

Adds JWT signature verification example to Inbound Proxy guide.

feat: add jwt example to inbound proxy

---

docs/api/proxies/pre-configured-proxies.mdx
docs/api/reactors/reactor-formulas.mdx
docs/api/reactors/reactors.mdx

se-231 feat: update code examples from single quotes to backticks

---

docs/api/reactors/reactors.mdx
docs/api/webhooks/eventdata.mdx
docs/concepts/what-are-reactors.mdx

- Documents the changes to the async reactor functionality.

feat: Convert async reactor callback url into proper webhook

---

docs/concepts/what-is-the-proxy.mdx

fix: update custom hostname guide

---

docs/api/proxies/proxies.mdx

se-228 feat: Update the detokenization amount in proxies to 20 instead of 100

---

docs/sdks/mobile/react-native/components.mdx
package.json
yarn.lock

- feat: adds keyboardType to rn card* elements
- chore: upgrade deps

feat: adds keyboardType to rn card* elements

---

docs/api/webhooks/api.mdx
docs/api/webhooks/webhooks.mdx

- Adds `notify_email` documentation to API
- Adds a paragraph describing automatically disabled webhooks

feat: add notify email to webhooks

---

docs/api/3ds/sessions.mdx

- Adds new session `type` prop on docs
- Adds the create 3ds session request to docs

feat: add 3ds session type and create session docs

---

docs/api/proxies/pre-configured-proxies.mdx

fix: remove legacy alert

---

docs/api/3ds/_test-cards.mdx

- Adds new Ravelin Luhn Valid [Test Cards](https://developer.ravelin.com/merchant/guides/3d-secure/test-cards/#3ds-2-test-cards-passes-luhn-check)

feat: add new ravelin test cards

---

docs/api/3ds/_test-cards.mdx
docs/api/3ds/sessions.mdx
docs/api/tokens/_bin-details-test-cards.mdx
docs/api/tokens/token-enrichments.mdx

- Remove useless bin details test card columns
- Add alert about 3ds cards being on bin details
- Add card brand to 3ds cards for bin details

feat: enhancements to test cards

---

docs/api/enrichments/bank-accounts.mdx
docs/api/tokens/token-enrichments.mdx
sidebars.js

- Adds API documentation for the `POST /enrichments/bank-account-verify` endpoint

feat: Add documentation for Bank Account Verification

---

docs/api/webhooks/eventdata.mdx

- Updates the `proxy.invoked` documentation regarding the new enhancements.
Describing the errors

feat: Add enhanced proxy.invoked documentation

---

docs/guides/process/authenticate-with-3ds.mdx
docs/sdks/index.mdx
docs/sdks/mobile/3ds/index.mdx
docs/sdks/mobile/3ds/methods.mdx
package.json
sidebars.js
yarn.lock

feat: adds 3DS mobile SDKs 

---

docs/sdks/web/javascript/events.mdx
docs/sdks/web/react/events.mdx

feat: adds errors to metadata

---

docs/guides/process/authenticate-with-3ds.mdx
docs/sdks/mobile/3ds-react-native/index.mdx
docs/sdks/mobile/3ds-react-native/methods.mdx
sidebars.js

- Adds docs for 3DS react native

feat: add docs for 3ds react native

---

docs/expressions/filters.mdx
docs/expressions/proxy.mdx
sidebars.js

- documenting proxy expressions

feat: documenting proxy expressions

---

docs/api/3ds/sessions.mdx
docs/api/webhooks/eventdata.mdx
docs/guides/process/authenticate-mit-with-3ds.mdx
docs/guides/process/authenticate-with-3ds.mdx
sidebars.js

- Adds guide for 3DS MIT
- Adds missing decoupled challenge props and event

feat: add mit guide and props

---

docs/api/rate-limits.mdx

se-243 removing info note in rate limits page

---

docs/api/proxies/proxies.mdx

fix: document trailing slash behavior

---

docs/guides/share/process-card-payments.mdx

feat: add flexfactor example

---

docs/api/tokens/tokenize.mdx
docs/api/tokens/tokens.mdx

- Documents the `_extras` property on token and tokenize.

feat: Document token _extras

---

docs/features/identity.mdx
docs/features/sso/index.mdx
sidebars.js

- Add feature page for identity features
- Add enforce SSO section to SSO page

feat: add identity feature page

---

.github/workflows/deploy.yml

- ci update to deploy notification

ci: update deploy notification

---

docs/api/webhooks/eventdata.mdx

- Adds documentation for the `timeout` attribute on `proxy.updated` event data.

feat: Add timeout setting to proxy.updated event data

---

.github/workflows/pull-requeset.yml

- Migrate to shared security workflows

chore: migrate to shared security workflows

---

docs/api/tokens/search.mdx

- fix search v2 container syntax

eng-7795 fix search v2 container syntax

---

docs/api/tokens/_card_details.mdx
docs/api/tokens/token-enrichments.mdx
docs/api/tokens/token-intents.mdx
docs/api/tokens/tokens.mdx
docs/sdks/_card-brands.mdx
docs/sdks/mobile/ios/types.mdx
docs/sdks/mobile/react-native/components.mdx

https://linear.app/basis-theory/issue/ENG-7834/update-documentation
Adding Card and Additional Information to Token and Token Intent
Updating supported brands  to Token and Token Intent
Adding information about differences between brands in vault and sdks
Enrichment Note about standardize format:

ENG-7834: Adding documentation for Card properties

---

docs/api/3ds/_test-cards.mdx

- removing wrong test card number

removing wrong test card number

---

docs/sdks/web/web-elements/index.mdx

fix: web elements cdn paths

---

docs/guides/apple-pay/accept.mdx

- fix: remove sdk list from apple pay/accept

fix: remove sdk list

---

docs/api/3ds/_test-cards.mdx

fix: sort 3ds test cards by luhn and scenario

---

docs/api/tokens/detokenize.mdx

- Updates detokenization limit setting description

Eng-7909: updates detokenization limit setting description

---

docs/api/orchestration/google-pay.mdx
docs/api/tokens/token-intents.mdx
docs/api/tokens/token-types.mdx
sidebars.js

- Adds documentation for Google Pay tokenziation
- I *think* I have followed all of the rules that Google is looking for defined here: https://developers.google.com/pay/api/processors/guides/test-and-validation/developer-documentation-checklist
New Token Type

feat: Document Google Pay Tokenization

---

docs/sdks/web/3ds/index.mdx

- adds disableTelemetry to 3DS Web SDK

adds disableTelemetry to 3DS Web SDK

---

docs/api-legacy/account-updater/account-updater.mdx
docs/api-legacy/tokens/token-intents.mdx
docs/concepts/what-are-reactors.mdx
docs/concepts/what-is-search.mdx
docs/features/3d-secure.mdx
docs/features/account-updater.mdx
docs/features/global-data.mdx
docs/features/network-tokens.mdx
docs/guides/process/authenticate-with-3ds.mdx
docs/sdks/_card-brands.mdx
docs/sdks/index.mdx
docs/sdks/mobile/3ds/index.mdx
docs/sdks/mobile/android/types.mdx
docs/sdks/mobile/ios/events.mdx
docs/sdks/mobile/ios/index.mdx
docs/sdks/mobile/ios/options.mdx
docs/sdks/mobile/ios/types.mdx
docs/sdks/mobile/react-native-threeds/index.mdx
docs/sdks/mobile/react-native-threeds/methods.mdx
docs/sdks/mobile/react-native/components.mdx
docs/sdks/web/3ds/index.mdx
docs/sdks/web/3ds/methods.mdx
docusaurus.config.js
sidebars.js
src/components/sdks/GithubCard.module.css
src/components/shared/Card.module.css
src/components/shared/Card.tsx

- feat: rename 3ds packages 
- refactor: replace `’` with `'`

feat: rename 3ds packages 

---

docs/guides/process/authenticate-with-3ds.mdx

fix: add 3ds auth condition

---

docs/blueprints/cards/issue-and-display-cards.mdx
docs/concepts/elements.mdx
docs/guides/collect/collect-cards-with-your-inputs.mdx
docs/guides/collect/collect-data-with-ios.mdx
docs/guides/collect/collect-data-with-react-native-on-ios.mdx
docs/sdks/index.mdx
docs/sdks/mobile/ios/index.mdx
docs/sdks/mobile/ios/types.mdx

feat: rename ios elements

---

docs/sdks/web/web-elements/services.mdx

- feat: add sessions to web-elements

feat: add sessions to web-elements

---

docs/api/tokens/token-intents.mdx
docs/concepts/token-intents.mdx

- Update docs after allow more then card token type in token-intent
https://developers.basistheory.com/docs/concepts/token-intents
https://developers.basistheory.com/docs/api/tokens/token-intents

chore(eng-7496): update docs after allow more then card token type in token-intent

---

docs/api/webhooks/eventdata.mdx
docs/sdks/web/3ds/index.mdx
docs/sdks/web/3ds/methods.mdx

- Adds the new method and challenge completed events to the list
- Remove `challengeContainerOptions` from 3DS SDK
- Add `containerId` to 3DS SDK `startChallenge`

feat: add new 3ds events, sdk changes

---

docs/api/tokens/_card_details.mdx
docs/api/tokens/token-intents.mdx

- Add issuer_country into token-intent and token object

chore(eng-8035): add issuer_country into token-intent and token object

---

docs/api/tokens/tokens.mdx

- Remove statement about references remaining for audit purposes.

Remove statement about references remaining for audit purposes.

---

docs/api/3ds/sessions.mdx
docs/guides/process/authenticate-mit-with-3ds.mdx
docs/guides/process/authenticate-with-3ds.mdx

adding additional details for going live pre-reqs

---

docs/blueprints/cards/collect-and-process-cards.mdx
docs/concepts/elements.mdx
docs/guides/banks/collect-bank-accounts.mdx
docs/guides/collect/collect-cards-single-element.mdx
docs/guides/collect/collect-cards-with-your-inputs.mdx
docs/guides/collect/collect-cards.mdx
docs/guides/collect/collect-data-with-react.mdx
docs/guides/collect/customize-web-form.mdx
docs/guides/collect/set-card-pin.mdx
docs/guides/share/display-cards.mdx
docs/guides/share/reveal-data-from-third-party.mdx
docs/guides/share/reveal-tokenized-data.mdx
docs/sdks/index.mdx
docs/sdks/mobile/3ds/methods.mdx
docs/sdks/mobile/react-native-threeds/methods.mdx
docs/sdks/web/3ds/methods.mdx
docs/sdks/web/javascript/index.mdx
docs/sdks/web/react/components.mdx
docs/sdks/web/react/index.mdx
docs/sdks/web/react/services.mdx
docs/sdks/web/web-elements/types.mdx
package.json
src/components/sdks/BasisTheoryComponentDisplay.tsx
yarn.lock

- feat: add react-elements
- deprecates [@basis-theory/basis-theory-react](https://github.com/Basis-Theory/basis-theory-react)

feat: add react-elements

---

docs/sdks/web/web-elements/index.mdx
src/components/sdks/GithubCard.tsx
src/components/sdks/WebElementsCdnExample.tsx
src/css/bt-variables.scss

- feat(web-elements): improve example when loading via cdn

feat(web-elements): improve example when loading via cdn

---

docs/guides/collect/collect-cards.mdx
docs/guides/share/display-cards.mdx
docs/sdks/index.mdx
docs/sdks/mobile/react-native/components.mdx
docs/sdks/mobile/react-native/index.mdx
docs/sdks/mobile/react-native/services.mdx

- feat: update react-native-elements docs

feat: update react-native-elements docs

---

docs/api/3ds/sessions.mdx

- adding better descriptions for 3ds auth codes

feat: adding better descriptions for 3ds auth codes

---

docs/sdks/web/web-elements/index.mdx
src/components/sdks/GithubCard.module.css
src/components/sdks/GithubCard.tsx
src/components/sdks/WebElementsCdnExample.tsx

- feat: add sri to github card and web elements cdn example

feat: add sri to github card and web elements cdn example

---

docs/api/tokens/_bank_details.mdx
docs/api/tokens/token-intents.mdx

- Adding Bank Details Documentation into Token Intents

ENG-8176: Adding Bank Details Documentation into Token Intents

---

docs/api/tokens/tokens.mdx

- Adding Bank Details on Token documentation

ENG-8183: Adding bank details on token documentation

---

docs/guides/collect/collect-data-from-web.mdx
docs/guides/collect/set-card-pin.mdx
docs/guides/govern/sessions.mdx
docs/sdks/web/javascript/index.mdx
docs/sdks/web/react/events.mdx
docs/sdks/web/react/index.mdx
docs/sdks/web/react/services.mdx
docs/sdks/web/web-elements/services.mdx

- fix: update react docs to reflect current state of sdk's

fix: update react docs to reflect current state of sdk's

---

docs/sdks/web/react/events.mdx
docs/sdks/web/react/index.mdx
docs/sdks/web/react/services.mdx

- fix: more react elements types

fix: more react elements types

---

docs/sdks/web/react/properties.mdx
docs/sdks/web/web-elements/options.mdx

- docs(elements): add more details to elements validation

docs(elements): add more details to elements validation

---

docs/guides/apple-pay/accept-payments.mdx

fix: apple checkout example

---

docs/api/webhooks/eventdata.mdx

ENG-8191: Adding `elapsed_ms` and `status` description  for proxy event data

---

docs/api/tokens/tokens.mdx

- Remove reference to short date format
- Updating deletion SLA and referencing token.expired event

fix: more corrections to token expiration docs

---

docs/api/connections/apple-pay.mdx
docs/api/connections/google-pay.mdx
docs/guides/apple-pay/accept-payments.mdx
docs/guides/google-pay/accept-payments.mdx

feat: Update permissions for Google and Apple Pay

---

docs/api/tokens/_card_details.mdx

chore(eng-8307): add issuer and segment into card details table

---

docs/guides/production-checklist.mdx

Maintaining the Prod checklist with latest guidelines

fix: update prod checklist

---

docs/card-payments/sections/_first-charge-section.mdx
docs/card-payments/sections/_subsequent-charges-section.mdx

fix: psp sample

---

docs/api/rate-limits.mdx

fix: limits docs

---

docs/api/connections/apple-pay.mdx

fix: Fix endpoint method

---

docs/api/3ds/sessions.mdx
docs/guides/threeds/implementation-cit.mdx
docs/sdks/mobile/3ds/methods.mdx
docs/sdks/mobile/react-native-threeds/methods.mdx
docs/sdks/web/3ds/methods.mdx

- Add documentation around co-badged cards for 3DS

feat: add 3ds cobadged cards docs

---

docs/api/network-tokens/network-tokens.mdx
sidebars.js

- Adding new network token section

ENG-8237: Adding network token documentation

---

docs/sdks/web/web-elements/initialization.mdx

- feat: add next/nuxt examples

feat: add next/nuxt examples

---

docs/sdks/web/web-elements/initialization.mdx

feat: framework support alert

---

docs/api/network-tokens/network-tokens.mdx
docs/api/tokens/token-intents.mdx
docs/api/tokens/tokens.mdx

- Adding support for `token_id` and `token_intent_id` in Network Token Request
- Adding relationship between token and token intent with network token ids

ENG-8508: Adding new attributes to network token

---

docs/api/reactors/reactor-dependencies.mdx
docs/api/reactors/reactors.mdx
docs/sdks/web/javascript/index.mdx

- updates BT.js version and config options for Reactors

fix: adds Node SDK and config options for Reactors

---

docs/api/network-tokens/network-tokens.mdx

ENG-8510: Adding Test Card Numbers for NT

---

docs/api/apple-pay/api.mdx
docs/guides/apple-pay/accept-payments.mdx

fix: URL path; remove /tokenize

---

docs/sdks/web/web-elements/components.mdx

- fix: css supported properties

fix: css supported properties

---

docs/sdks/web/web-elements/components.mdx
docs/sdks/web/web-elements/troubleshooting.mdx

- feat: add elements release 1.14.1

feat: add elements release 1.14.1

---

docs/api/network-tokens/network-tokens.mdx

ENG-8586: Adding extras object for NTs

---

docs/sdks/web/web-elements/components.mdx

fix(elements): supported validation types

---

docs/api/account-updater/batch.mdx
docs/api/account-updater/real-time.mdx

- adds docs for batch and real time account updater deduplication

feat: adds docs for batch and real time account updater deduplication

---

docs/api/network-tokens/network-tokens.mdx
docs/api/proxies/ephemeral-proxy.mdx
docs/api/proxies/pre-configured-proxies.mdx
docs/api/proxies/proxies.mdx
docs/api/reactors/reactors.mdx

ENG-8674: Adding Error Title column for Test Cards + Updating `proxy:invoke` and `reactor:invoke` doc

---

docs/api/network-tokens/network-tokens.mdx

- Adding Network Token Suspend/Resume documentation

ENG-8076: Adding Suspend/Resume Network Token documentation

---

docs/sdks/server-side/go.mdx
docs/sdks/server-side/java.mdx

- fixing docs for go and java sdk

fixing docs for go and java sdk

---

docs/card-payments/sections/_generic-proxy-examples.mdx

Update docs NMI example docs MMYYYY to MMYY

---

docs/guides/apple-pay/tokenize-process-payment.mdx
docs/guides/google-pay/accept-payments.mdx

fix: apple stripe example

---

.gitignore
docusaurus.config.js
src/theme/DocItem/Header/index.js

- Better generation of content.mds and llms.txt

Updated llms.txt and generation

---

docusaurus.config.js

fixing markdown generation for index pages

---

docs/api/errors.mdx
docs/api/rate-limits.mdx

- Add error coded and limit information

ENG-8540: Add 408 timeout status code on errors table.

---

docs/api/proxies/ephemeral-proxy.mdx
docs/api/proxies/pre-configured-proxies.mdx

- Add documentation for ephemeral and pre-configured proxy

feat(eng-8366): add documentation to encrypted header in proxy request

---

docs/sdks/web/web-elements/initialization.mdx
docs/sdks/web/web-elements/troubleshooting.mdx

- feat: adds useNetworkCheck docs

feat: adds useNetworkCheck

---

docs/api/rate-limits.mdx

fix: Documents rate limit definition

---

docs/api/network-tokens/network-tokens.mdx

ENG-8854: Updating Network Token Cards

---

docs/sdks/mobile/ios/services.mdx
docs/sdks/mobile/react-native/services.mdx

- feat: add token intents to ios and react-native sdks

feat: add token intents to ios and react-native sdks

---

docs/api/apple-pay/api.mdx

fix: Use correct permissions for Apple Pay documentation

---

docs/api/documents/api.mdx

- Updates documents upload/download for node-sdk changes.

fix: Update documents node snippets

---

docs/api/network-tokens/network-tokens.mdx

fix: dns typo

---

docs/api/apple-pay/api.mdx
docs/api/connections/apple-pay.mdx
docs/api/connections/google-pay.mdx
docs/api/deprecations.mdx
docs/api/google-pay/api.mdx
docs/guides/apple-pay/accept.mdx
docs/guides/apple-pay/create-session.mdx
docs/guides/apple-pay/domain-verification.mdx
docs/guides/apple-pay/dpan-payments.mdx
docs/guides/apple-pay/mpan-payments.mdx
docs/guides/apple-pay/overview.mdx
docs/guides/apple-pay/payment-flow.mdx
docs/guides/apple-pay/setup.mdx
docs/guides/apple-pay/tokenize-process-payment.mdx
docs/guides/google-pay/accept-payments.mdx
sidebars.js

- Update Google Pay Guide to new API specification

feat: Update Google Pay Guide to new API specification

---

docs/guides/google-pay/accept-payments.mdx

- update GPay guide for GPay expressions

chore: update GPay guide for GPay expressions

---

docs/api/apple-pay/api.mdx
docs/api/applications/applications.mdx

- Add documentation for ApplePay DELETE endpoint

feat: Add documentation for ApplePay DELETE endpoint

---

docs/api/reactors/reactor-dependencies.mdx

fix: document p-limit

---

docs/sdks/web/web-elements/cobadge.mdx
docs/sdks/web/web-elements/components.mdx
docs/sdks/web/web-elements/events.mdx
sidebars.js

' Add documentation for Co Badge Support  in web elements

chore: Add docs for Co Badge Support on web elements
