docs/sdks/mobile/android/events.mdx
docs/sdks/mobile/android/index.mdx
docs/sdks/mobile/android/types.mdx

- Adds documentation for bin and last4 on change events and CardMetadata within the Android SDK
- Fixes error in installation instructions for Android SDK

feat: Documents bin/last4 in Android SDK

---

docs/api/tokens/tokens.mdx

Document ability to update `expires_at` on `PATCH /tokens` endpoint. Also change some relative paths / links to absolute links according to this [Slack thread in #Engineering](https://basistheory.slack.com/archives/C01HVEKV3LP/p1673029045016989).

fix: document ability to update expires_at on patch /tokens endpoint

---

docs/sdks/mobile/android/services.mdx
docs/sdks/mobile/android/types.mdx

- Document android create session, proxy and get a token services
- Document setValueRef with value references

feat: documenting android proxy and get a token services

---

src/components/docs/BlueprintCard.module.css
src/components/shared/Alert.module.css
src/css/footer.scss
src/css/tabs.scss
src/pages/index.module.css
src/pages/index.tsx
src/theme/Icon/Edit/styles.module.css

- drop usage of `:has` selector
- rename classes for clarity

fix: drop usage of `:has` selector

---

docs/api/testing.mdx
sidebars.js

- Documents testing recommendations
- Documents test card numbers

feat: Adds Testing page

---

docs/blueprints/cards/index.mdx
docs/blueprints/cards/issue-and-display-cards.mdx
docs/guides/process/extract-data.mdx
sidebars.js

- Changes title for display virtual cards blueprint
- Change some wording on the blueprint

fix: change wording, title for display cards blueprint

---

docs/sdks/mobile/ios/types.mdx

- update incorrect card brands for ios and js

feat: update card brands

---

docs/expressions/filters.mdx
docs/sdks/mobile/android/types.mdx
docs/sdks/mobile/ios/events.mdx
docs/sdks/web/javascript/methods.mdx

- Documents new filters and card bin length updates

feat: new filters and updating card bin length outputs

---

docs/sdks/web/javascript/content-security-policy.mdx

- added more generic csp to accommodate change from elements to js domains

fix: updating csp

---

docs/sdks/server-side/java.mdx

Noticed while following the SDK docs the Gradle example appears to have the incorrect repsitory provided, updated as per that provided on https://www.jitpack.io/#Basis-Theory/basistheory-java/0.4.0

Update example Gradle repository

---

docs/sdks/mobile/ios/services.mdx

- feat: adds raw proxy response to iOS
- [] Not Applicable

feat: adds raw proxy response to iOS

---

docs/sdks/mobile/ios/options.mdx
docs/sdks/mobile/ios/types.mdx

- Adds docs for the enableCopy and copyIconColor attributes in iOS.

feat: add ios enableCopy docs

---

docs/sdks/mobile/ios/options.mdx
docs/sdks/mobile/ios/types.mdx

- Adds docs for getValueType for iOS SDK.
- Adds warning about changing value type to `Int` for `month()` and `year()` methods in exp date element (iOS).

feat: add ios getValueType docs

---

docs/sdks/mobile/android/options.mdx
docs/sdks/mobile/android/types.mdx

Adds docs for `getValueType` for Android SDK.
Adds warning about changing value type to `Int` for `month()` and `year()` methods in exp date element (Android).

feat: add android getValueType docs

---

docs/guides/share/display-cards.mdx

- fix: explicitly set readOnly to `true`

fix: explicitly set readOnly to `true`

---

docs/api/proxies/ephemeral-proxy.mdx
docs/api/tenants/tenants.mdx

- Add small alert on the Ephemeral Proxy page indicating ephemeral proxies can be disabled.
- Add documentation in the TenantSettings object section on the Tenants page.
- Add `disable_ephemeral_proxy` attribute to code samples on Tenants page.
https://developers.basistheory.com/docs/api/proxies/ephemeral-proxy
https://developers.basistheory.com/docs/api/tenants/#tenant-settings-object

Add documentation for ephemeral proxy disable

---

docs/guides/collect/issue-cards.mdx

fix: uses alias in card issuance flow

---

docs/guides/collect/issue-cards.mdx

feat: add adyen issuing example

---

docs/guides/process/authenticate-with-3ds.mdx
docs/sdks/web/3ds/methods.mdx

- Adds `timeout` prop and information about it for 3DS `startChallenge`.

feat: add timeout prop for 3ds start challenge

---

docs/guides/apple-pay/accept-payments.mdx
docs/guides/google-pay/accept-payments.mdx

- Adds curl examples for Stripe in Apple Pay and Google Pay guides.

feat: Add Stripe example to google and apple pay docs

---

docs/api/tokens/tokens.mdx

- updating token expiration date format; while short dates and non-standard formats are supported by the API, they are non-standard. We should only be documenting usage of standard ISO 8601 formatted dates

fix: updating token expiration date format
